### ISSUE TITLE
broken master

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-ui#29]
current master is broke on circleci

https://circleci.com/gh/openzipkin/zipkin-ui/57

This may or may not be related to a concern raised on gitter by @charlescui
> I git clone zipkin-ui from github, but the master branch is not a stable source code. I npm run build meet many error, such as package.json didn't contain moment package , webpack version is not locked and error with webpack.common.js options. Is there a stable version?

**Comment by adriancole** [comment]
trying "rebuild without cache" in circleci

**Comment by adriancole** [comment]
this fixes the build but I don't think the CSS is right. help wanted on last mile here https://github.com/openzipkin/zipkin-ui/pull/30

**Comment by charlescui** [comment]
I fixed `npm run build` error with issue #31 .

**Comment by devinsba** [comment]
@apottere pointed out that all the dev dependencies in our `package.json` are version `*`, which means that it would be impossible for our builds to be repeatable across people and computers. It would be nice for one of the UI devs to explain that decision because I know there must be a reason for it.

@rogeralsing looks like that is your code
